[package]
name = "rust_clowncryption"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.1"
aes-gcm-siv = "0.11.1"
base64 = "0.21.0"
crypto = "0.4.0"
hex = "0.4.3"
